---
title: "spatialdv-vignette"
author: "Flávio Mota"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{spatialdv-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction
*spatialdv* is a package created to calculate diversity patterns for spatial data.

## Creating random data to test the package
```{r}
library(terra)
library(spatialdv)

# creating SpatRaster objects for reference and future scenarios
set.seed(100)
ref <- rast(array(sample(c(rep(1, 750), rep(0, 250))), dim = c(10, 10, 10)))
ref

fut <- rast(array(sample(c(rep(1, 300), rep(0, 700))), dim = c(10, 10, 10)))
fut

# creating data.frame object with species traits
mass <- runif(10, .5, 2)
elev <- sample(500:1000, 10)
traits <- as.data.frame(cbind(mass, elev))
rownames(traits) <- paste0("sp", 1:nrow(traits))
traits
```

## Calculating alpha diversity
```{r, fig.height = 5, fig.width = 5, fig.align = 'center',}
# alpha diversity for reference scenario
spatialdv(ref, fut, "alpha1")

# alpha diversity for future scenario
spatialdv(ref, fut, "alpha2")

# difference between future and reference scenarios
spatialdv(ref, fut, "delta")
```

## Calculating beta diversity
```{r, fig.height = 5, fig.width = 5, fig.align = 'center',}
# total beta diversity between scenarios
spatialdv(ref, fut, "beta")

# turnover component
spatialdv(ref, fut, "turn")

# nestedness component
spatialdv(ref, fut, "nest")

# ratio (turnover/total beta diversity)
spatialdv(ref, fut, "ratio")
```

## Calculating trait generalization
```{r, fig.height = 5, fig.width = 5, fig.align = 'center',}
# body mass ecological generalization
spatialgn(ref, traits, "mass")

# elevation ecological generalization
spatialgn(ref, traits, "elev")
```
